### PR TITLE
[READY] Create growth hacker job

### PR DESCRIPTION
**Pull request by RonaldDijkstra**

### CODE REVIEW

**Comment by RonaldDijkstra** [comment]
A few things
- short copy I got from @Jeenine, this is the way Hans wants it online
- I made this PR through the interface because (pushing to) Github got some troubles this afternoon

**Comment by fatboypunk** [comment]
> short copy I got from @Jeenine, this is the way Hans wants it online

I guess that has to be added?

**Comment by RonaldDijkstra** [comment]
No, this is all.

**Comment by fatboypunk** [comment]
I think we can use some of the other texts like the about us and some of the things that we expect could be more explicit

**Comment by RonaldDijkstra** [comment]
Spelling mistake in the title, sorry. 
I will add the about after talking to some people tomorrow.

**Pull request closed without merging**
